source 'https://rubygems.org'
ruby "2.7.2"
# gem 'pry'
# gem 'rack'
# gem 'rack-test'
# gem 'rspec'
# gem 'rack-cors'
# gem 'shotgun'

# gem "sinatra-activerecord"
# gem "sqlite3"
gem "require_all", "~> 3.0"
gem "activerecord", "~> 5.2"
gem "pry", "~> 0.14.1"
gem "sinatra-activerecord", "~> 2.0"
gem "sqlite3", "~> 1.4"

gem "rack", "~> 2.2"

gem "rack-cors", "~> 1.1"

gem "shotgun", "~> 0.9.2"


gem "pg", "~> 1.2"
