source 'https://rubygems.org'

# gem 'pry'
# gem 'rack'
# gem 'rack-test'
# gem 'rspec'
# gem 'rack-cors'
# gem 'shotgun'

# gem "sinatra-activerecord"
# gem "sqlite3"
gem "require_all", "~> 3.0"
gem "activerecord", "~> 5.2"
gem "pry", "~> 0.14.1"
gem "sinatra-activerecord", "~> 2.0"
gem "sqlite3", "~> 1.4"
